### ISSUE TITLE
Compilation fails due to missing dependency

### ISSUE THREAD

**Issue by TomMD** [lizhuohua/rust-mir-checker#1]
Hello, just wanting to try out the tool and I can't get it to compile (not a Rust user here, more interested in the yet-another-static-analysis tool angle).   The issue:

```
$ cargo install --path .
  Installing rust-mir-checker v0.1.0 (/home/lift/rust-mir)
    Updating crates.io index
   Compiling rust-mir-checker v0.1.0 (/home/lift/rust-mir)
error[E0463]: can't find crate for `rustc_ast`
 --> src/lib.rs:7:1
  |
7 | extern crate rustc_ast;
  | ^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```

Adding to the cargo.toml didn't help since the ast package itself didn't build with this nightly.

**Comment by lizhuohua** [comment]
I guess you need to install the `rustc-dev` component using `rustup`:

```
rustup component add rustc-dev
```

**Comment by TomMD** [comment]
Hurm, oddities but it's all about my system.
