### ISSUE TITLE
cargo install error

### ISSUE THREAD

**Issue by echos2019** [lizhuohua/rust-mir-checker#12]
hello author,
I cant build this project by "cargo install --path ." the error like this:
```
error: failed to compile `rust-mir-checker v0.1.0 (/home/dell/rust/rust-mir-checker)`, intermediate artifacts can be found at `/home/dell/rust/rust-mir-checker/target`

Caused by:
  failed to download `object v0.30.3`

Caused by:
  unable to get packages from source

Caused by:
  failed to download replaced source registry `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to parse manifest at `/home/dell/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/object-0.30.3/Cargo.toml`

Caused by:
  feature `resolver` is required

  consider adding `cargo-features = ["resolver"]` to the manifest
```
I try to add `cargo-features = ["resolver"]` ,but cant fix this problem, and try to install object v0.30.3 by offline, but the error still exists
I want to check projects built by cargo ,so I hope you can help me fix this problem

**Comment by Koral77** [comment]
@echos2019 Have you fixed the problem? I also encountered the same problem.

**Comment by echos2019** [comment]
> @echos2019 Have you fixed the problem? I also encountered the same problem.

I have no idea. it can only run by `cargo run mir-checker .....` ,cant analyze program which uses `use` or `extern crate`
If you have some idea, please share with me, I'm looking forward to your reply
